CREATE TABLE gestao_eventos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100)   NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    data_hora DATETIME     NOT NULL,
    local VARCHAR(200)     NOT NULL,
    deleted boolean DEFAULT 0,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);
