spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mirante
    username: root
    password: root

  flyway:
    enabled: true
    rapair: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api





project:
  version: '@project.version@'
  description: '@project.description@'
  name: '@project.name@'
